# Generated by Django 4.2.2 on 2023-07-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_cart_razorpay_order_id_cart_razorpay_payment_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart", old_name="status", new_name="cart_status",
        ),
        migrations.RemoveField(model_name="cart", name="payment",),
        migrations.AddField(
            model_name="cart",
            name="payment_status",
            field=models.BooleanField(default=False),
        ),
    ]
